# Generated by Django 4.1.8 on 2023-05-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pemasukan',
        ),
        migrations.DeleteModel(
            name='Pengeluaran',
        ),
    ]
