# Generated by Django 4.1.8 on 2023-05-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_delete_pemasukan_delete_pengeluaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='pemasukan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField(verbose_name='%d-%m-%y')),
            ],
        ),
        migrations.CreateModel(
            name='pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField()),
            ],
        ),
    ]
