# Generated by Django 4.1.8 on 2023-05-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pemasukan',
            table='pemasukan',
        ),
        migrations.AlterModelTable(
            name='pengeluaran',
            table='pengeluaran',
        ),
    ]
